spring:
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
  application:
    name: spring-ai-cat-study
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring-ai-chat-cat?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
      username: root
      password: hsp
  ai:
#    vectorstore:
#      redis:
#        initialize-schema: true
    tools:
      observations:
        include-content: true
    openai:
      chat:
        options:
          model: qwen-max-latest
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024

      base-url:  https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPNEAI_API_KEY}
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
#root??????debug???
logging:
  level:
#    org.springframework.ai.chat.client.advisor: DEBUG #?????debug
#    org.springframework.ai.tool: DEBUG #?????debug
    org.springframework.ai: DEBUG #?????debug
    org.springframework.ai.tool: DEBUG #?????debug
    org.springframework.ai.chat.client.advisor: DEBUG #?????debug
    com.zzcat.springaicatstudy : DEBUG #?????debug
server:
  port: 8080
